### ISSUE TITLE
does not contain copyright notice

### ISSUE THREAD

**Issue by stormchaser3000** [AndrejIT/chat_anticurse#1]
this project should contain a copyright notice

**Comment by AndrejIT** [comment]
Now i added info about creator and license information in init.lua, is that ok as copuright notice?

**Comment by stormchaser3000** [comment]
i was thinking more of this. 

one line to give the library's name and an idea of what it does.
Copyright (C) year  name of author

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

"If you develop a new library, and you want it to be of the greatest possible use to the public, we recommend making it free software that everyone can redistribute and change. You can do so by permitting redistribution under these terms (or, alternatively, under the terms of the ordinary General Public License)." (https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html)

**Comment by stormchaser3000** [comment]
btw that last part in quotes would not be part of the copyright notice. and also the mod should contain a copy of the license.

if you copy the license from here https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt which should be easier than copying a bunch of HTML crap that would work

**Comment by AndrejIT** [comment]
Ok, i added licence file.
Looks like there are many different styles of how to compose descriptions, licence and author, i need to observe more, and pick my own style. Anyway, i will try to make my next mods look more respectable.
